name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: kirschbaumdevelopment/laravel-test-runner:8.2
    name: Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix Git ownership
        run: git config --global --add safe.directory /__w/laravel-online-payment-platform/laravel-online-payment-platform

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Execute tests (replay mode)
        run: composer replay